### ISSUE TITLE
Expand subpackages - multiple levels

### ISSUE THREAD

**Issue by FreHu** [marcellourbani/abapPretty#2]
My main package only contains subpackages which contain further development objects. abapPretty will not expand the subpackages correctly.

```
abappretty simulate -c BQ5 DEVC/K XXXX

Expanding package XXXX... Done

0 of 0 objects / 0 includes processed 0 written
```

**Comment by marcellourbani** [comment]
Can you provide a testcase?
Does the vscode extension work on those?

**Comment by FreHu** [comment]
Nevermind, I didn't specify the recursive parameter.
